print("Character A: \t\"Hello there!\"")
print("Character B: \t\"Hi! how are you?\"")
print("Character A: \t\"I\'m doing great.\' Thanks for asking!\"")
print("Character C: \t\"Hey, what\'s going on?\"")
print("Character B: \t\"We were just catching up.\"")
print("Character A: \t\"Yeah, it\'s been a while.\"")
print("Character C: \t\"Nice to see you both!\"")
print("Character B: \t\"Likewise! How have you been?\"")
print("Character C: \t\"I\'ve been good. Thanks!\"")
print("Character A: \t\"That\'s great to hear.S\"")

recipient = input("Enter the recipient: ")
msg = input("Enter the message: ")
name = input("Enter the name: ")
subject = input("Enter the subject: ")
version = float(input("Enter the version: "))
discount = float(input("Enter the discount: "))
status = input("Enter the code: ")
code = input("Enter the code: ")
location = input("Enter the location: ")
age = int(input("Enter the age: "))
company = input("Enter the company name: ")
website = input("Enter the website: ")
phone = int(input("Enter the phone: "))
jobTitle = input("Enter the job title: ")
department = input("Enter the department: ")

print(f"Dear{recipient}, I hope this email finds you well.")
print(f"{msg}")
print(f"Subject: {subject}")
print(f"Sender: {name}")
print(f"Version: {version}")
print(f"Discount: {discount}")
print(f"Status: {status}")
print(f"Code: {code}")
print(f"Location: {location}")
print(f"Age: {age}")
print(f"Company: {company}")
print(f"Website: {website}")
print(f"Phone: {phone}")
print(f"Job Title: {jobTitle}")
print(f"Department: {department}")