recipient = input("Enter the recipient: ")
msg = input("Enter the message: ")
name = input("Enter the name: ")
subject = input("Enter the subject: ")
version = float(input("Enter the version: "))
discount = float(input("Enter the discount: "))
status = (input('Enter the Status: '))
code = input("Enter the code: ")
location = input("Enter the location: ")
age = int(input("Enter the age: "))
company = input("Enter the company name: ")
website = input("Enter the website: ")
phone = input("Enter the phone: ")
jobTitle = input("Enter the job title: ")
department = input("Enter the department: ")

print(f"Dear {recipient}, I hope this email finds you well.")
print(f"{msg}")
print(f"Subject: {subject}")
print(f"Sender: {name}")
print(f"Version: {version}")
print(f"Discount: {discount:.2f} %")
print(f"Status: {status}")
print(f"Code: {code}")
print(f"Location: {location}")
print(f"Age: {age}")
print(f"Company: {company}")
print(f"Website: {website}")
print(f"Phone: {phone}")
print(f"Job Title: {jobTitle}")
print(f"Department: {department}")